user: rogerio@vimeo.com
password-source: keyring
endpoint: https://vimean.atlassian.net
project: VIM
qa_user: rogerioassis
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --template mine --query "sprint in openSprints() or sprint in futureSprints() and assignee=currentuser() ORDER BY created"
  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi
  - name: ready
    help: Moves a given issue to the Ready for QA column
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} transition --noedit "Ready for QA" {{args.ISSUE}}
      {{jira}} assign {{args.ISSUE}} $JIRA_QA_USER
  - name: go
    help: Creates a feature branch and moves a given issue to the Dev in progress column
    options:
      - name: type
        default: feature
    args:
      - name: ISSUE
        required: true
      - name: DESC
        required: true
    script: |-
      git flow {{options.type}} start {{args.ISSUE}}_{{args.DESC}}
      {{jira}} transition --noedit "Started" {{args.ISSUE}}
  - name: env
    script: |
      env | grep JIRA