user: rogerio.assis@tinybeans.com
endpoint: https://tinybeanskids.atlassian.net
project: GROWTH
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --template mine --query "sprint in openSprints() and sprint not in futureSprints() and assignee=currentuser() ORDER BY created"
  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          echo "\"project: ...\" configuration missing from .jira.d/config.yml"
      fi