#!/bin/bash

hook_name=`basename "$0"`
project_folder=`git rev-parse --show-toplevel`
protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
local_hook="$project_folder"/.hooks/"$hook_name"

# Check if pushing to a master branch and ask for manual confirmation
if [ $protected_branch = $current_branch ]; then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
      exit 0
    fi
    exit 1
else
    exit 0
fi

# Load any local project hooks
if [ -f "$local_hook" ]; then
  . "$local_hook"
fi
